[build]
  base = "trash_apps/app"
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "../../trash_apps/netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"